### ISSUE TITLE
mgs16S by SRA sample feature table

### ISSUE THREAD

**Issue by sjanssen2** [tillrobin/iMGMC#1]
Hi,
thanks to your great resource, I could match one differential abundant PacBio fulllength 16S feature to your mgs16S-0293. You assign the taxonomy Bacteria;Bacteroidetes;Bacteroidia;Bacteroidales;Rikenellaceae;Alistipes to it and I'd love to find our more about this specific bug. 
Your Graphical Abstract says something about 168,573 SRA samples as input for your pipeline. Do you have some table lists prevalence of mgs16S-0293 in all those samples?
I am looking for something like our S6 table with more than the 11 broad categories.
Thanks in advance,
Stefan

**Comment by tillrobin** [comment]
Dear Stefan,
yes this information you can find here:
https://github.com/tillrobin/iMGMC/blob/master/IMNGS.md
https://onedrive.live.com/download?cid=36ADEB4B3D109F6F&resid=36ADEB4B3D109F6F%2133933&authkey=AEcUb0Y4AtC8HfI

In addition you can start with mgs16S-0293 a new IMNGS (https://www.imngs.org/) run to get prevalence of newer samples.

Best Till Robin
