### ISSUE TITLE
final-unambiguousReads.tab does not get created

### ISSUE THREAD

**Issue by Unaimend** [tillrobin/iMGMC#10]
The file
 "final-unambiguousReads.tab" does not get created. Also, there is no mention of it in the script from the screenshot below

![image](https://user-images.githubusercontent.com/7808379/204367757-d215a3ae-78a1-43d8-b36c-f27642de9038.png)

from the linking tutorial.
Maybe that's an error in the documentation

**Comment by tillrobin** [comment]
Hi Unaimend,
the pipeline is very old and would suggest to used now bwa2-mapping, please see example:
https://github.com/tillrobin/iMGMCv2
As alternative nice abundance estimation pipeline are in development:
https://github.com/wwood/CoverM

Best Till Robin
