### ISSUE TITLE
An issue in Mapping part

### ISSUE THREAD

**Issue by magcurly** [tillrobin/iMGMC#2]
I couldn't run bbmap if follow the command you mentioned in genecatalog-pipeline.md. 
my BBmap version=38.86
```
bbmap.sh -Xmx30g unpigz=t threads=${usedCores} minid=0.90 \
ref=${iMGCM-data} nodisk \
statsfile=${SampleName}.statsfile \
scafstats=${SampleName}.scafstats \
covstats=${SampleName}.covstat \
rpkm=${SampleName}.rpkm \
sortscafs=f nzo=f \
in=${SampleName}_R1_rmhost.fastq.gz \
in2=${SampleName}_R2_rmhost.fastq.gz
```
I have to use "path" instead of "ref". Otherwise, BBmap fails to find the index.
Besides, I don't know whether it happened in your system, but minus symbol could not use in RedHat as an environment variable name.
Hope I can hear from you soon.

**Comment by tillrobin** [comment]
Dear Zhu,
you can use the "ref" parameter after the first run or a separate index step (bbmap.sh path=${iMGCM-data}). This save time if you have more than one sample.
The - memory parmeter you can set if you work on shared systems, to limit memory use, see bbmap documentation (see below).  You can try without this parameter. 

Hope this information is helpful, best Till Robin
 
Java Parameters:
-Xmx                    This will be passed to Java to set memory usage, overriding the program's automatic memory detection.
                        -Xmx20g will specify 20 gigs of RAM, and -Xmx200m will specify 200 megs.  The max is typically 85% of physical memory.
