### ISSUE TITLE
Using the pre-build links between 16S rRNA genes with metagenome-assembled genomes?

### ISSUE THREAD

**Issue by BinhongLiu** [tillrobin/iMGMC#3]
Hi,
   It's really an exciting tool for the mouse gut microbiome analysis! In my study, I have obtained the 16S rRNA gene V3-V4 amplicon sequencing data of C57BL/6J mice. I'm trying to use the pre-build links between 16S rRNA genes with metagenome-assembled genomes in iMGMC. In the paper,  full-length, unique 16S rRNA gene sequences were used to build the links with metagenome-assembled genomes. I'm wondering if my 16S rRNA amplicon sequencing data could also employ this tool to get the metagenome-assembled genome informations? With this pipeline _[Instruction to process your own WGS samples with iMGMC](https://github.com/tillrobin/iMGMC/blob/master/genecatalog-pipeline.md)_? Many thanks!
Regards!

**Comment by tillrobin** [comment]
Hello,
yes one target of iMGMC was to use genome information for 16S rRNA gene sequencing. You have different options:
1: PICRUSt to get functional predictions: https://github.com/tillrobin/iMGMC/tree/master/PICRUSt , see an example application in this study: Jiang, P., Green, S.J., Chlipala, G.E. et al. Reproducible changes in the gut microbiome suggest a shift in microbial and host metabolism during spaceflight. Microbiome 7, 113 (2019). https://doi.org/10.1186/s40168-019-0724-4
2: You can preform close-ref picking to the reconstruced 16S rRNA sequencing and the links  to the MAGs:
https://github.com/tillrobin/iMGMC/blob/master/PICRUSt/iMGMC-MAGs16SrRNAlinks.tab
3: Simulation of metagenomic libraries, see our publications:
Fritz, A.,  et al. CAMISIM: simulating metagenomes and microbial communities. Microbiome 7, 17 (2019). https://doi.org/10.1186/s40168-019-0633-6
F. Meyer,  et al.: Tutorial: Assessing metagenomics software with the CAMI benchmarking toolkit
bioRxiv 2020.08.11.245712; doi: https://doi.org/10.1101/2020.08.11.245712

Hope this informations are useful for you,
Best Till Robin
