### ISSUE TITLE
Gene/ORF coordinates 

### ISSUE THREAD

**Issue by alexcrofts** [tillrobin/iMGMC#4]
Hello, I see how the .tab files connect genes and their associated function/taxonomy to the contigs they were annotated in, but is there coordinate information available that describes where in those contigs each ORF starts/stops? Thanks for info you have!

**Comment by tillrobin** [comment]
Hello alexcrofts,
sure, I upload the coordinates output of metagenemark here:
https://1drv.ms/u/s!Am-fED1L6602g-8EW9Svccp9DBIcdg?e=9Vl67W
Maybe reformating is needed.
last position is the contig ID/Nr
>gene_19415|GeneMark.hmm|120399_nt|-|64577|184975       >MegahitA5_81
>gene_52212|GeneMark.hmm|106452_nt|+|3214|109665        >MegahitA5_309
>gene_79273|GeneMark.hmm|103611_nt|+|9032|112642        >MegahitA5_559

Best Till

**Comment by alexcrofts** [comment]
Thank you!
