### ISSUE TITLE
PICRUSt2 compatible files

### ISSUE THREAD

**Issue by alow711** [tillrobin/iMGMC#5]
Hi Till

I get the error "usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: picrust pynast fasttree" when I key conda create iMGMC-PICRUSt -c bioconda picrust pynast fasttree
Do you know how to solve this issue?

Also I would like to use PICRUSt 2 with my amplicon sequences with your reference database. Do you have the PICRUST2 ready files in the following format? 
pro_ref.fna.gz
pro_ref.hmm
pro_ref.model
pro_ref.tre

If not, I would greatly appreciate some guidance on how to get the files ready for PICRUST2.

thank you, kind regards
Adrian

**Comment by tillrobin** [comment]
Hi Adiran,
sorry there is a error in the bioconda command:
"conda create iMGMC-PICRUSt -c bioconda picrust pynast fasttree"
correct version:
"conda create -n iMGMC-PICRUSt -c bioconda picrust pynast fasttree"

PICRUSt2 is on my toDo list.

Best Till
