### ISSUE TITLE
Mice specific 16S database for metabarcoding taxonomic assignments

### ISSUE THREAD

**Issue by fconstancias** [tillrobin/iMGMC#6]
Dear iMGMC developers,

Thanks for developing this amazing tool.
I was wondering if I could use iMGMC tool/data in order to assign 16S V4 ASV against a reduced, mice-specific microbiota database.  
I obtained those ASV using the dada2 pipeline und ultimately would like to assign taxonomy using `DECIPHER::IdTaxa()`.
So I would need a fasta file with mice specific 16S sequences as well as the taxonomic path.

Does it sound feasable? Would you suggest another alternative?

Thanks a lot for your help.

Flo

**Comment by tillrobin** [comment]
Thanks Flo,
this is a nice idea. We provide the 1323 reconstructed 16S-rRNA-genes fasta (https://zenodo.org/record/3631711/files/iMGMC-16SrRNAgenes.fasta) in the download selection and the taxonomic information in Table S6 in the paper (https://ars.els-cdn.com/content/image/1-s2.0-S2211124720301972-mmc7.xlsx).
However, the size is quite small and you will loss taxonomic assignments compared to Greengenes/Silva/EzTaxon that contain much more reference sequences. The resolution of eg. v4 is maybe too low to benefit from environment specific species. Moreover, many of this 16S-rRNA-gene reference sequences leak any species description. But feel free to try, eg we enrich the standard 16S databases with specific mouse 16S-rRNA-genes.

Best regards
Till Robin
