### ISSUE TITLE
Further stratification

### ISSUE THREAD

**Issue by alexcrofts** [tillrobin/iMGMC#7]
Hello,

Great database, thank you! 

1) I see in the summary image in the pipeline/tutorial section "KO Pathway" is listed for the functions section , although I don't see a way to arrange the KO annotations into pathways using the current tools - is that something that is still being worked on or am I missing the script for it somewhere here? Do I need to move my data into some KEGG specific pipeline to get pathway sums?

2) Is there an easy way to stratify KOs by taxonomy? I can get taxonomy TPM sums, and KO TPM sums, but it's not clear to me how to get KO sums by taxonomy.  Thanks for any info you can provide!

**Comment by tillrobin** [comment]
Dear Alex,
sorry for the late response. A split of reads into taxonomy and functional annotation is possible. Both annotations you can find in the mapping files. Create first a TPM-file for your samples; check the functional mapping files for the gene IDs you are looking for. Now you can just “grep” the IDs from the TPM file.

Best Till Robin
