### ISSUE TITLE
Submit genomes to NCBI

### ISSUE THREAD

**Issue by SilasK** [tillrobin/iMGMC#8]
Hello, thank you for this great resource. If I'm not mistaken, you didn't submit your genomes to NCBI. I know it can be difficult sometimes. But the advantage of genomes submitted to NCBI is that they are incorporated in GTDB and other databases ..

If you provide me with a table with the NCBI sample names we can upload your genomes to NCBI and link it to your publication/Bioproject. 

Kind regards

CC @ trickovicmatija

**Comment by tillrobin** [comment]
Dear Silas,
Thanks for the interest in our catalog. We uploaded our raw reads to the SRA. MAGs are created also from external public data, sometimes there are already MAGs available or will get an updated version form projects like MGnify. Therefor we uploaded to static doi record like common for bigger MAG studies. However, we will may be consider this for our own libraries.

Best Till Robin

**Comment by tillrobin** [comment]
Hi Silas,
as the solution all MAGs will be integrated into MGnify https://www.ebi.ac.uk/metagenomics/

Best Till Robin
