### ISSUE TITLE
Template filepath does not exist: iMGMC-16SrRNA-alignment.fasta

### ISSUE THREAD

**Issue by elayton13** [tillrobin/iMGMC#9]
Hello,

I am trying to use iMGMC for picrust analysis using the following code:

conda create -n iMGMC-PICRUSt -c bioconda picrust pynast fasttree
./iMGMC-PICRUSt.bash run2_feature.biom run2_sequences.fasta

As detailed in the picrust information page. But it seems I am missing a number of required files such as:
iMGMC-CopyNr-16SrRNA.tab
iMGMC-KO_traits.tab
along with a number of other traits files

I can't seem to find these files as part of the downloads on here - am I supposed to generate these somehow?

Thanks for your advice

**Comment by tillrobin** [comment]
Dear Elayton,
this files are part of this repositorie and you can see on the site:
https://github.com/tillrobin/iMGMC/tree/master/PICRUSt

Best Till

**Comment by elayton13** [comment]
Hi Till

Thanks for the quick reply, sorry I missed that. I am still having some issues with missing files and packages, please see some of the error message below:

./iMGMC-PICRUSt.bash /home/emma/iMGMC/run2_feature.biom /home/emma/iMGMC/run2_sequences.fasta
/home/emma/iMGMC
mkdir: cannot create directory ‘run2_feature’: File exists
Traceback (most recent call last):
  File "/home/emma/anaconda3/envs/iMGMC-PICRUSt/bin/pynast", line 194, in <module>
    main()
  File "/home/emma/anaconda3/envs/iMGMC-PICRUSt/bin/pynast", line 178, in main
    for seq, status in pynast_iterator:
  File "/home/emma/anaconda3/envs/iMGMC-PICRUSt/lib/python2.7/site-packages/pynast/util.py", line 651, in ipynast_seqs
    current_result = pw_alignment_iterator.next()
  File "/home/emma/anaconda3/envs/iMGMC-PICRUSt/lib/python2.7/site-packages/pynast/pycogent_backports/uclust.py", line 399, in uclust_search_and_align_from_fasta_filepath
    TmpDir=tmp_dir,HALT_EXEC=HALT_EXEC)
  File "/home/emma/anaconda3/envs/iMGMC-PICRUSt/lib/python2.7/site-packages/cogent/app/util.py", line 166, in __init__
    self._error_on_missing_application(params)
  File "/home/emma/anaconda3/envs/iMGMC-PICRUSt/lib/python2.7/site-packages/cogent/app/util.py", line 435, in _error_on_missing_application
    % command
cogent.app.util.ApplicationNotFoundError: Cannot find uclust. Is it installed? Is it in your path?
cat: iMGC-16S-alignment.fasta: No such file or directory

Is the  iMGC-16S-alignment.fasta supposed to be the iMGMC-16SrRNA-alignment.fasta? I have tried downloading uclust from the website, copying it to my directory and making it executable, but it seems there is still an issue with this. Any advice on this would be appreciated

Best wishes
Emma

**Comment by tillrobin** [comment]
Hi Emma,
The best would be to clone the full repository or download the full zip. Change to the folder <YouPath>/iMGMC/PICRUSt/. Now all files should be there. Please write again if you have still problems.
The pipeline is quite old, sometime new updates in bioconda make problems, but PATH problems should be resolvable.

Best Till

**Comment by elayton13** [comment]
Hi Till,

I'm still getting the same error message even after cloning the repository. Any ideas on what I could try next? Do you expect the issue is to do with the pynast / uclust installs?

Best wishes
Emma

**Comment by tillrobin** [comment]
Hi Emma,
PyNAST was not updated since 2018, that problem is maybe the newer Python version. Try to rebuild the enviroment with old Python 2.7:
conda create -n iMGMC-PICRUSt -c bioconda picrust pynast fasttree python=2.7

Hope this will help.

Best Till

**Comment by elayton13** [comment]
Hi Till,

Tried this but still the same issue, do you have any other suggestions please?

Thanks
Emma

**Comment by tillrobin** [comment]
Dear Emma,
I checked again. The problem is the depending of pynast to uclust executable,  but it's no longer available, see:
[executable uclust](https://github.com/biocore/pynast/issues/21)

Please get in direct contact with me:
https://www.helmholtz-hzi.de/en/nc/service/contact/person/till-robin-lesker/

Best Till
